steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - my-nodejs-app  # function mame GCP
      - --region=europe-west1 # Region
      - --source=.
#      - --trigger-http       # Если это веб-страница (HTTP-триггер)
      - --runtime=nodejs222   # version of  Node.js
      - --allow-unauthenticated # If public build

options:
  logging: CLOUD_LOGGING_ONLY